p8105_hw1_jc6452
================

# Problem 1

## importing data

``` r
data("penguins", package = "palmerpenguins")
summary(penguins)
```

    ##       species          island    bill_length_mm  bill_depth_mm  
    ##  Adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
    ##  Chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
    ##  Gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
    ##                                  Mean   :43.92   Mean   :17.15  
    ##                                  3rd Qu.:48.50   3rd Qu.:18.70  
    ##                                  Max.   :59.60   Max.   :21.50  
    ##                                  NA's   :2       NA's   :2      
    ##  flipper_length_mm  body_mass_g       sex           year     
    ##  Min.   :172.0     Min.   :2700   female:165   Min.   :2007  
    ##  1st Qu.:190.0     1st Qu.:3550   male  :168   1st Qu.:2007  
    ##  Median :197.0     Median :4050   NA's  : 11   Median :2008  
    ##  Mean   :200.9     Mean   :4202                Mean   :2008  
    ##  3rd Qu.:213.0     3rd Qu.:4750                3rd Qu.:2009  
    ##  Max.   :231.0     Max.   :6300                Max.   :2009  
    ##  NA's   :2         NA's   :2

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

``` r
print(mean(penguins$flipper_length_mm, na.rm = TRUE))
```

    ## [1] 200.9152

## description of *penguins* dataset

The *penguins* dataset includes the following 8 variables,
species,island, bill_length_mm, bill_depth_mm, flipper_length_mm,
body_mass_g, sex, and year. Some of the notable values of the variables
include is that the earliest year listed is 2007 and mean values for
bill_length, bill_depth and flipper_length is 43.92, 17.15, 200.9,
respectively. The penguins in this dataset weigh an average of 4202g
(4.202kg). The dataset size is (344 x 8), which means in contains 8
columns and 344 rows total. The mean flipper length is 200.9152, after
removing the NA entries.

## creating penguins scatterplot

``` r
ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

![](p8105_hw1_jc6452_files/figure-gfm/scatterplot-1.png)<!-- -->

``` r
ggsave('penguins_flipper_blil_plot.png')
```

    ## Saving 7 x 5 in image

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

# Problem 2

## creating tibble

``` r
df = 
  tibble(
  x = rnorm(10),
  vector_logical = c(x>0),
  vector_character = c("this", "is", "P8105", "data", "science", "data", "wrangling", "homework", "one", "problem"),
  vector_factor = c("low", "high", "high", "medium", "medium", "low", "high", "high", "low", "medium")
)
sample = pull(df, x)
pull_VL = pull (df, vector_logical)
pull_VC = pull(df, vector_character)
pull_VF = pull(df, vector_factor)

mean(sample)
```

    ## [1] 0.04970298

``` r
mean(pull_VL)
```

    ## [1] 0.5

``` r
mean(pull_VC)
```

    ## Warning in mean.default(pull_VC): argument is not numeric or logical: returning
    ## NA

    ## [1] NA

``` r
mean(pull_VF)
```

    ## Warning in mean.default(pull_VF): argument is not numeric or logical: returning
    ## NA

    ## [1] NA

The character vector and factor vector cannot be computed by the mean
function.

## numeric logical, character and factor vector

``` r
numeric_vl = as.numeric(pull_VL)
numeric_vc = as.numeric(pull_VC)
```

    ## Warning: NAs introduced by coercion

``` r
numeric_vf = as.numeric(pull_VF)
```

    ## Warning: NAs introduced by coercion

``` r
mean(numeric_vl)
```

    ## [1] 0.5

``` r
mean(numeric_vc)
```

    ## [1] NA

``` r
mean(numeric_vf)
```

    ## [1] NA

According to the warning message, “NAs introduced by coercion”, and both
the character vector and factor vector, which has been applied with
`as.numeric` function, outputted NA when I tried to compute the mean.
This is because these are string type variables where the values inside
the variable such as `pull_VC` or `pull_VF`, are string and as they are
descriptive, and non-numerical. Unlike the two, logical vector outputted
mean of 0.5 as logical vector is boolean, hence its output can be
computed in numerical term (0 when FALSE and 1 when TRUE). When viewing
the `mean` function, there are methods for numeric/logical vectors, and
date, date-time and time interval objects. Therefore, character and
factor vectors cannot be computed while logical vectors can be.
